### ISSUE TITLE
Connecting within Lambda

### ISSUE THREAD

**Issue by jamiearonson** [mergermarket/acuris-aws-es-connection#1]
Tried updating from the old Node client and came across this package. I am able to connect locally, but once my Lambda is deployed to AWS the connection is refused. I have ensured that the Lambda's execution IAM role has the proper access.

I was just curious if you'd tested this within a Lambda before I dug too much deeper.

**Comment by fewstera** [comment]
Hi @jamiearonson, we're using this on one of our profuction lambdas here at Acuris.

Below is how we setup the client for our lambdas (**note**: it's typescript):

```
import { createAWSConnector, awsCredsifyAll } from 'aws-es-connection'
import { Client } from '@elastic/elasticsearch'
import AWS from 'aws-sdk'

export function createElasticsearchClient({ endpoint }: { endpoint: string }): Client {
  const AWSConnector = createAWSConnector(AWS.config.credentials as AWS.Credentials)
  return awsCredsifyAll(
    new Client({
      node: endpoint,
      Connection: AWSConnector
    })
  )
}
```

**Comment by jamiearonson** [comment]
Thanks @fewstera for the quick response. Repurposing your example not only fixed my issue, but also removes the async call to get the creds.

**Comment by montumodi** [comment]
Hi,
Aplogies for commenting on this close issue. We are also using this package for our AWS elasticearch. The code mentioned above works fine for AWS Lambda but gives following error on AWS EC2 instance

```
TypeError: Cannot read property 'getPromise' of null
    at Client.search (/tmp/test/node_modules/@acuris/aws-es-connection/dist/index.js:37:18)
```

Our EC2 instance has all the necssary IAM roles. Can you recommend something here? Looks like credentials is coming as null but not sure why.

**Comment by Hammo1337** [comment]
@montumodi do you have an example of this working in AWS Lambda, regardless of configuration I seem to be getting 403 returned, the IAM roles are setup correctly.

**Comment by montumodi** [comment]
403 is generally when your policy isn't setup properly. Can you send your policy?

**Comment by AwolDes** [comment]
@fewstera is that example you have still current for Lambda? Trying to get this going and not having any luck with it, or with the example you have in the README.

```js
const esClient = async () => {
  try {
    const awsCredentials = await awsGetCredentials();
    const AWSConnection = createAWSConnection(awsCredentials);

    return new Client({
      ...AWSConnection,
      node: process.env.ES_NODE,
    });
  } catch (e) {
    console.log(e);
    throw Error(e);
  }
};

// Later, in an async func, still timing out.
const client = await esClient();
const result = await client.search...
```

**Comment by AwolDes** [comment]
Update: fixed this by deleting my ES cluster, then creating a new one with a VPC config. This allowed the Lambda to work, but local access is no broken. For those following this thread in the future, look here: https://www.jeremydaly.com/access-aws-vpc-based-elasticsearch-cluster-locally/

I intend to just use a docker instance locally.
