### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by realworld666** [mergermarket/acuris-aws-es-connection#10]
I had some working code that could access my AWS elasticsearch domain to write to an index and search it. Now I'm trying to add authentication and using this package my code no longer works. I get a rather vague "Response Error. Code 403" Have I missed something obvious?

```
const credentials = new Credentials(MY_ACCESS_KEY_ID, MY_SECRET_KEY);
  const AWSConnection = createAWSConnection(credentials);
  client = awsCredsifyAll(
    new Client({
      Connection: AWSConnection,
      node: 'https://MY_AWS_NODE.us-east-2.es.amazonaws.com/'
    }));

  client.ping({}, { requestTimeout: 20000 }, (err: any, response: any) => {
    if (err) {
      console.log(err);
    } else {

      beginSetupIndexes().catch(console.log);
      // performSearch().catch(console.error);
    }
  });
```

I get the error 403 in the ping() callback

```
{ ResponseError: Response Error
    at IncomingMessage.response.on (node_modules\@elastic\elasticsearch\lib\Transport.js:240:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  name: 'ResponseError',
  meta: 
   { body: true,
     statusCode: 403,
     headers: 
      { date: 'Wed, 02 Sep 2020 10:36:37 GMT',
        'content-type': 'application/json; charset=UTF-8',
        'content-length': '415',
        connection: 'keep-alive',
        'access-control-allow-origin': '*' },
     warnings: null,
     meta: 
      { context: null,
        request: [Object],
        name: 'elasticsearch-js',
        connection: [Object],
        attempts: 0,
        aborted: false } } }
Debugger attached.
Waiting for the debugger to disconnect...

Process finished with exit code 0

```

**Comment by fewstera** [comment]
Is it possible to get the response body? Try JSON.stringify() on the error, or maybe logging err.body.

If you're hard coding the access_key_id and secret_access_key then you don't need to use awsCredsifyAll, but that shouldn't cause any issues.

My guess would be that your access policy on the ES domain doesn't allow the IAM user to perform the action you're trying to perform.

**Comment by realworld666** [comment]
err.body just says "true"

**Comment by fewstera** [comment]
Does your IAM user / role have permission to use elasticsearch?

Can you see if the HTTP response has a body other than true?

**Comment by realworld666** [comment]
I've tracked down the issue. The domain also had basic auth enabled so it was being rejected at that step because I wasn't passing through the master user and password. I've reset everything and setup again and got it working now. Thank you

**Comment by fewstera** [comment]
Glad you got it fixed @realworld666
