### ISSUE TITLE
"has no default import" issue

### ISSUE THREAD

**Issue by tonivdv** [mergermarket/acuris-aws-es-connection#4]
Hi,

When I'm compiling the code with this library I get:

```shell
node_modules/@acuris/aws-es-connection/dist/index.d.ts:1:8 - error TS1192: Module '"/Users/..../node_modules/aws-sdk/index"' has no default export.

1 import AWS from 'aws-sdk';
         ~~~
```

I'm pretty new to typescript so I could be mistaken ... but when I change following line

https://github.com/mergermarket/acuris-aws-es-connection/blob/d86660e626d64add3c9d9374ca60378d0f41543a/src/index.ts#L1

into

```typescript
import * as AWS from 'aws-sdk';
```

I don't have the error anymore ....

Am I doing something wrong in my project or is it something to improve here?

**Comment by tonivdv** [comment]
After some deeper research it seems there is an option in the ts compiler to accept this notation ...

```json
{
  "compilerOptions": {
    ...
    "allowSyntheticDefaultImports": true,
    ...
  },
  ...
}
```

Not sure if my issue above should ideally be fixed or not?! But at least I'm unblocked 😅

**Comment by fewstera** [comment]
Thank you for writing this issue. That flag is the right one to fix this issue.

We probably shouldn't be using that flag in this module if it's causing issues for our users.

I'll raise a PR to fix this. Thank you.

**Comment by tonivdv** [comment]
That was fast :) Many thanks.
