### ISSUE TITLE
AWS Signing not working with CNAME / A outside us-east-1

### ISSUE THREAD

**Issue by dcgomesbr** [mergermarket/acuris-aws-es-connection#43]
I suspect this module is not working properly when using a Custom Endpoint with a CNAME / A in regions other than 'us-east-1'.

Wen configuring the Route53, I tried both CNAME record to the VPC endpoint and A record to the respective IP. When trying to open a connection, this error is logged:

```
Credential should be scoped to a valid region, not 'us-east-1'. Credential should be scoped to correct service: 'es'. 
```

The error can be replicated by creating a Custom Endpoint in AWS ElasticSearch in a region other than 'us-east-1', having with a proper ACM certificate for the Custom Endpoint and try to connect to it.

Using the regular VPC endpoint works just fine.

Do not forget to set the AWS SDK region in first place:
```
  AWS.config.update(new Config({ region: 'some-region' }));
```

**Comment by hanvyj** [comment]
I think I'm having a similar issue accessing through a ssh tunnel, I believe it's because the `hostname` it's signing doesn't match up when authenticating etc.

**Comment by arunvishnun** [comment]
@hanvyj @dcgomesbr I am having same issue. Did you find any workarounds ?
