### ISSUE TITLE
Does @elastic/elasticsearch still need to be capped to 7.9.1?

### ISSUE THREAD

**Issue by jasonwalkeryung** [mergermarket/acuris-aws-es-connection#56]
First, thank you for writing this package! It's been working great for a project I'm working on. However, I was wondering why package.json caps the `@elastic/elasticsearch` dependency at 7.9.1. I saw that it wasn't working with 7.9.1 briefly, but it looks like you resolved that. We're using 7.11.0 and it works just fine (even with the unit test). We're happy to submit a PR but it looks like a quick change to your end.

**Comment by aterreno** [comment]
I doubt @jasonwalkeryung  I've opened a PR to address that https://github.com/mergermarket/acuris-aws-es-connection/pull/57

**Comment by andrewwood2** [comment]
Thanks @jasonwalkeryung for your interest in this project and thanks @aterreno for the PR. 
The reason for fixing the version was that the breaking change in the elastic/elasticsearch 7.9.1 package took us by surprise and caused a few problems for us, and potentially a few other teams using it. We felt that by fixing the peer dependency to one we had tested we could save everyone some pain. 
I will look to test the PR asap and get a new version released!

**Comment by andrewwood2** [comment]
A new version 2.2.1 has been released to fix this issue.

**Comment by aterreno** [comment]
Awesome thanks Andrew
