### ISSUE TITLE
typeError: Cannot read property 'getPromise' of null

### ISSUE THREAD

**Issue by montumodi** [mergermarket/acuris-aws-es-connection#7]
Hi,
Thanks for making this package. Till now we were using `http-aws-es` and it was all fine. We decided to upgrade es and native es client package so we thought of using this package. We have two use cases

- Calling it from Lambda
- Calling it from EC2

Code below works fine from AWS lambda but gives error while using it from EC2 box.

```
const {Client} = require("@elastic/elasticsearch");
const {createAWSConnection, awsCredsifyAll} = require("@acuris/aws-es-connection");

const AWSConnection = createAWSConnection(AWS.config.credentials);

const elasticsearchConfig = {
  "node": "elastic-url"
  "Connection": AWSConnection
};

const nativeClient = awsCredsifyAll(new Client(elasticsearchConfig));

nativeClient.search({index: "someindex", "body": {}}).then(res => console.log(res));

```

This is the error we recieve

```
TypeError: Cannot read property 'getPromise' of null
    at Client.search (/tmp/test/node_modules/@acuris/aws-es-connection/dist/index.js:37:18)
```

Please note that EC2 has correct set of permissions so no issue around that. Looks like AWS credentials are coming as null.

Can you please help here?

**Comment by fewstera** [comment]
On EC2 you will need to wait for the credentials to be fetched, you can use the helper method provided.

‘’’
const awsCredentials = await awsGetCredentials()
const AWSConnection = createAWSConnection(awsCredentials)
‘’’

On EC2 fetching credentials is an async operation, which is why you’re seeing null if you’re trying to use AWS.config.credentials

**Comment by montumodi** [comment]
Thanks for quick reply. Unfortunately this will cause a breaking change on the internal driver we have created as I will need to make the function `async` to accomodate this change.

**Comment by fewstera** [comment]
Unfortunately you need to have the credentials available to start using this package, so you’ll need to refactor to using an async creator.
